apiVersion: v1
kind: Service
metadata:
  name: balance-service-lb
spec:
  type: LoadBalancer
  selector:
    app: balance-service
  ports:
    - port: 9092
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service-deployment
  labels:
    app: balance-service
spec:
  selector:
    matchLabels:
      app: balance-service
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: balance-service
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: balance-service-container
          image: aklahoti/balance-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
