apiVersion: v1
kind: Service
metadata:
  name: gateway-security-lb
spec:
  type: LoadBalancer
  selector:
    app: gateway-security
  ports:
    - port: 9090
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-security-deployment
  labels:
    app: gateway-security
spec:
  selector:
    matchLabels:
      app: gateway-security
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway-security
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: gateway-security-container
          image: aklahoti/gateway-security:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
